name: ble_multimeter
description: A Flutter app to connect to BLE Multimeter
publish_to: 'none'
version: 1.0.0+1 

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.0
  google_fonts: ^6.2.1
  lottie: ^3.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.0
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/loader.json